# Generated by Django 6.0.5 on 2026-05-22 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва курсу')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код курсу')),
                ('credits', models.PositiveIntegerField(default=3, verbose_name='Кредити')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курси',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Номер студентського')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Дата зарахування')),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='university.course', verbose_name='Курси')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенти',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('exam', 'Іспит'), ('test', 'Залік'), ('homework', 'Домашнє завдання'), ('lab', 'Лабораторна робота'), ('project', 'Курсовий проект')], max_length=10, verbose_name='Тип оцінки')),
                ('score', models.PositiveIntegerField(verbose_name='Бал (0-100)')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='university.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='university.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Оцінка',
                'verbose_name_plural': 'Оцінки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('department', models.CharField(max_length=200, verbose_name='Кафедра')),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name='Дата прийому на роботу')),
            ],
            options={
                'verbose_name': 'Викладач',
                'verbose_name_plural': 'Викладачі',
                'indexes': [models.Index(fields=['last_name'], name='idx_teacher_lastname'), models.Index(fields=['department'], name='idx_teacher_dept')],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('lecture', 'Лекція'), ('practice', 'Практика'), ('lab', 'Лабораторна'), ('seminar', 'Семінар')], max_length=10, verbose_name='Тип заняття')),
                ('topic', models.CharField(max_length=300, verbose_name='Тема')),
                ('date', models.DateTimeField(verbose_name='Дата та час')),
                ('room', models.CharField(max_length=50, verbose_name='Аудиторія')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='university.course', verbose_name='Курс')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='university.teacher', verbose_name='Викладач')),
            ],
            options={
                'verbose_name': 'Заняття',
                'verbose_name_plural': 'Заняття',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='courses', to='university.teacher', verbose_name='Викладачі'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name'], name='idx_student_lastname'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='idx_student_id'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'course'], name='idx_grade_student_course'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('score__lte', 100)), name='grade_score_max_100'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['date'], name='idx_lesson_date'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'date'], name='idx_lesson_course_date'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='idx_course_code'),
        ),
    ]
